apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: flask-weatherapp-uat
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - pullRequest:
        github:
          owner: omidiyanto
          repo: flask-weatherapp
          # tokenRef:
          #   key: token
          #   secretName: github-token # (2)
        requeueAfterSeconds: 10
  template:
    metadata:
      name: "flask-weatherapp-{{ .branch_slug }}-{{ .number }}"
      namespace: argocd
    spec:
      source:
        repoURL: https://github.com/omidiyanto/gitops-configuration-repository.git
        targetRevision: HEAD
        path: apps/flask-weatherapp
        helm:
          parameters:
            - name: namespace
              value: 'flask-weatherapp-{{ .branch_slug }}-{{ .number }}'
            - name: image.tag
              value: '{{ .head_sha }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: "flask-weatherapp-{{ .branch_slug }}-{{ .number }}"
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true