apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: flask-weatherapp-uat
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - pullRequest:
        github:
          owner: omidiyanto
          repo: flask-weatherapp
          labels:
            - preview
        requeueAfterSeconds: 60
  template:
    metadata:
      name: "flask-weatherapp-{{ .branch_slug }}-{{ .number }}"
      namespace: argocd
    spec:
      source:
        repoURL: https://github.com/omidiyanto/flask-weatherapp.git
        targetRevision: "{{ .head_sha }}"
        path: helm/flask-weatherapp
      destination:
        server: https://kubernetes.default.svc
        namespace: "flask-weatherapp-{{ .branch_slug }}-{{ .number }}"
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
