apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-weatherapp
spec:
  selector:
    matchLabels:
      app: golang-weatherapp
  template:
    metadata:
      labels:
        app: golang-weatherapp
    spec:
      containers:
      - name: golang-weatherapp
        image: nginx:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
