apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: production
replicas:
  - name: app1
    count: 3
patchesStrategicMerge:
  - resources.yaml
images:
  - name: ${IMAGE_REPOSITORY}/app1:${IMAGE_TAG}
    newName: ${IMAGE_REPOSITORY}/app1
    newTag: ${IMAGE_TAG} 